#!/bin/bash -eux
#!/bin/bash -eux

hash=$1
domain=$2

cd /data/domains/
wget https://wader.indie.host/migrate/$hash
unzip $hash
rm $hash

cd $domain

cp TLS/$domain.pem /system/haproxy/haproxy/certs

systemctl start u@$domain
systemctl enable u@$domain
