#!/bin/bash -eux

domain=$1
ip=$2
cd /data/domains/$domain
./BACKUP

systemctl stop u@$domain
systemctl disable u@$domain

tar cvzf /home/core/${domain}.tgz .
etcdctl --peers 172.17.42.1:4001 set /services/web/$domain '{"ip":"'$ip'", "port":"443"}'
